services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: highload-app
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://citus-master:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345678
    depends_on:
      master:
        condition: service_healthy
  master:
    container_name: "citus-master"
    image: "citusdata/citus:14.0.0"
    ports: ["5432:5432"]
    labels: ["com.citusdata.role=Master"]
    environment: &AUTH
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "12345678"
      PGUSER: "${POSTGRES_USER:-postgres}"
      PGPASSWORD: "12345678"
      POSTGRES_HOST_AUTH_METHOD: "${POSTGRES_HOST_AUTH_METHOD:-trust}"
  worker:
    image: "citusdata/citus:14.0.0"
    labels: ["com.citusdata.role=Worker"]
    environment: *AUTH
    volumes:
      - healthcheck-volume:/healthcheck
volumes:
  healthcheck-volume: