server:
  port: 8085
spring:
  application:
    name: counter
  datasource:
    url: jdbc:postgresql://localhost:7432/counter-db
    username: counter-user
    password: 12345678
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      idle-timeout: 30000
      pool-name: HikariCounterPool
      max-lifetime: 1800000
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  data:
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          max-active: 100
          max-idle: 20
          min-idle: 5
          max-wait: 1000ms
        shutdown-timeout: 100ms
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: counter-service-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        isolation.level: read_committed
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        enable.idempotence: true
        retries: 5
    topics:
      message-create: "message-create-topic"
      message-rollback: "message-rollback-topic"
logging:
  level:
    root: INFO